### ISSUE TITLE
Getting issue in main.ts only

### ISSUE THREAD

**Issue by decypherr** [neeravp/vue3-animate-in-view#1] opened 2021-07-20 10:20 UTC
ERROR  Failed to compile with 2 errors                                                             15:49:42

These dependencies were not found:

* @/components/AnimateInView.vue in ./node_modules/@neeravp/vue-3-animate-in-view/dist/vue-3-animate-in-view.esm.js
* @/directives/AnimateInView in ./node_modules/@neeravp/vue-3-animate-in-view/dist/vue-3-animate-in-view.esm.js

To install them, you can run: npm install --save @/components/AnimateInView.vue @/directives/AnimateInView
No issues found.
<img width="1440" alt="Screenshot 2021-07-20 at 3 50 34 PM" src="https://user-images.githubusercontent.com/83206196/126308024-79a32772-5bd1-486e-8bf3-40a8886e7e63.png">

**Comment by neeravp** [comment] 2021-07-20 18:04
Guess the README was some how not updated. Have updated the `Setup` in the README.

`AnimateInViewComponent` and `AnimateInViewDirective` are the exported  members so imports should be accordingly

```javascript
import { AnimateInViewComponent } from '@neeravp/vue-3-animate-in-view'
import { AnimateInViewDirective } from '@neeravp/vue-3-animate-in-view'
```

Please modify the import accordingly and let me know in comment if issue still persists

**Comment by neeravp** [comment] 2021-07-22 13:40
@decypherr Hope the issue is resolved for you.  If not please provide further feedback. 

In absence of further feedback from your end, assuming the issue is resolved at your end, shall proceed to close this issue ticket.

**Comment by neeravp** [comment] 2021-07-26 17:47
Closing this issue now @decypherr assuming it's resolved for you as there's been no further response from your end.

**Closed as completed by neeravp** 2021-07-26 17:47 UTC

**Comment by decypherr** [comment] 2021-07-27 03:57
Apologies, i didn’t checked the email… i will check if it works and will
update you..
